/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.presta;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Green
 */
public class PrestaInterfaz extends javax.swing.JFrame {

    /**
     * Creates new form PrestaInterfaz
     */
    
    public PrestaInterfaz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        paneles_presta = new javax.swing.JTabbedPane();
        panel_generarPrestamo = new javax.swing.JPanel();
        panel_prestamo = new javax.swing.JPanel();
        label_prestamo = new javax.swing.JLabel();
        scrollPane_materialesPrestamo = new javax.swing.JScrollPane();
        table_materialesPrestamo = new javax.swing.JTable();
        button_enviarPrestamo = new javax.swing.JButton();
        panel_material = new javax.swing.JPanel();
        label_generarPrestamoMaterial = new javax.swing.JLabel();
        comboBox_materiales = new javax.swing.JComboBox<>();
        textField_descripcion = new javax.swing.JTextField();
        comboBox_cantidad = new javax.swing.JComboBox<>();
        label_cantidad = new javax.swing.JLabel();
        label_potenciador = new javax.swing.JLabel();
        comboBox_Potenciador = new javax.swing.JComboBox<>();
        button_agregarMaterial = new javax.swing.JButton();
        panel_perfilUsuario = new javax.swing.JPanel();
        panel_informacionUsuario = new javax.swing.JPanel();
        textField_usuarioNombre = new javax.swing.JTextField();
        textField_usuarioEmail = new javax.swing.JTextField();
        textField_UsuarioTipo = new javax.swing.JTextField();
        panel_agregarMateriales = new javax.swing.JPanel();
        panel_inventario = new javax.swing.JPanel();
        scrollPane_inventario = new javax.swing.JScrollPane();
        table_inventario = new javax.swing.JTable();
        panel_agregarMaterial = new javax.swing.JPanel();
        textField_nombreMaterial = new javax.swing.JTextField();
        checkBox_Potencia = new javax.swing.JCheckBox();
        checkBox_descripcion = new javax.swing.JCheckBox();
        panel_consultarMisPrestamos = new javax.swing.JPanel();
        panel_filtroMateriales = new javax.swing.JPanel();
        comboBox_materialFiltro = new javax.swing.JComboBox<>();
        textField_descripcionFiltro = new javax.swing.JTextField();
        comboBox_estadoFiltro = new javax.swing.JComboBox<>();
        textField_numPrestadosFiltro = new javax.swing.JTextField();
        textField_numDevueltosFIltro = new javax.swing.JTextField();
        label_misPrestamosMaterial = new javax.swing.JLabel();
        label_estadoMaterial = new javax.swing.JLabel();
        panel_prestamos = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_prestamos = new javax.swing.JTable();
        panel_titulo = new javax.swing.JPanel();
        label_titulo = new javax.swing.JLabel();
        panel_nombreDelUsuario = new javax.swing.JPanel();
        label_nombreDelUsuario = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        paneles_presta.setBackground(new java.awt.Color(255, 255, 255));

        panel_generarPrestamo.setBackground(new java.awt.Color(255, 255, 255));

        panel_prestamo.setBackground(new java.awt.Color(255, 255, 255));

        label_prestamo.setText("Préstamo");

        table_materialesPrestamo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Material", "Descripción", "Potenciador", "Cantidad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrollPane_materialesPrestamo.setViewportView(table_materialesPrestamo);

        button_enviarPrestamo.setText("Enviar préstamo");

        javax.swing.GroupLayout panel_prestamoLayout = new javax.swing.GroupLayout(panel_prestamo);
        panel_prestamo.setLayout(panel_prestamoLayout);
        panel_prestamoLayout.setHorizontalGroup(
            panel_prestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_prestamoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_prestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_prestamoLayout.createSequentialGroup()
                        .addComponent(label_prestamo)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(scrollPane_materialesPrestamo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 542, Short.MAX_VALUE)))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_prestamoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(button_enviarPrestamo)
                .addContainerGap())
        );
        panel_prestamoLayout.setVerticalGroup(
            panel_prestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_prestamoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_prestamo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollPane_materialesPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(button_enviarPrestamo)
                .addContainerGap())
        );

        panel_material.setBackground(new java.awt.Color(255, 255, 255));

        label_generarPrestamoMaterial.setText("Material");

        comboBox_materiales.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        textField_descripcion.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        textField_descripcion.setText("descripción");
        textField_descripcion.setToolTipText("");
        textField_descripcion.setBorder(javax.swing.BorderFactory.createTitledBorder("Descripción"));

        comboBox_cantidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        label_cantidad.setText("Cantidad");

        label_potenciador.setText("Potenciador");

        comboBox_Potenciador.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "N/A", "Pico", "Nano", "Micro", "Mili", "Kilo", "Mega", "Giga", "Tera" }));

        button_agregarMaterial.setText("Agregar");

        javax.swing.GroupLayout panel_materialLayout = new javax.swing.GroupLayout(panel_material);
        panel_material.setLayout(panel_materialLayout);
        panel_materialLayout.setHorizontalGroup(
            panel_materialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_materialLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_materialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textField_descripcion)
                    .addGroup(panel_materialLayout.createSequentialGroup()
                        .addGroup(panel_materialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_generarPrestamoMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboBox_materiales, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(button_agregarMaterial)
                            .addGroup(panel_materialLayout.createSequentialGroup()
                                .addComponent(label_potenciador)
                                .addGap(18, 18, 18)
                                .addComponent(label_cantidad))
                            .addGroup(panel_materialLayout.createSequentialGroup()
                                .addComponent(comboBox_Potenciador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(comboBox_cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 67, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panel_materialLayout.setVerticalGroup(
            panel_materialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_materialLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_generarPrestamoMaterial)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboBox_materiales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textField_descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_materialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_potenciador)
                    .addComponent(label_cantidad))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_materialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBox_Potenciador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBox_cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(button_agregarMaterial)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        comboBox_Potenciador.getAccessibleContext().setAccessibleDescription("");

        javax.swing.GroupLayout panel_generarPrestamoLayout = new javax.swing.GroupLayout(panel_generarPrestamo);
        panel_generarPrestamo.setLayout(panel_generarPrestamoLayout);
        panel_generarPrestamoLayout.setHorizontalGroup(
            panel_generarPrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_generarPrestamoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel_material, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panel_prestamo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panel_generarPrestamoLayout.setVerticalGroup(
            panel_generarPrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_generarPrestamoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_generarPrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panel_prestamo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel_material, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(151, Short.MAX_VALUE))
        );

        paneles_presta.addTab("Generar Préstamo", panel_generarPrestamo);

        panel_perfilUsuario.setBackground(new java.awt.Color(255, 255, 255));

        panel_informacionUsuario.setBackground(new java.awt.Color(255, 255, 255));
        panel_informacionUsuario.setBorder(javax.swing.BorderFactory.createTitledBorder("Información De Perfil"));

        textField_usuarioNombre.setEditable(false);
        textField_usuarioNombre.setBorder(javax.swing.BorderFactory.createTitledBorder("Nombre:"));

        textField_usuarioEmail.setEditable(false);
        textField_usuarioEmail.setBorder(javax.swing.BorderFactory.createTitledBorder("Email:"));

        textField_UsuarioTipo.setEditable(false);
        textField_UsuarioTipo.setBorder(javax.swing.BorderFactory.createTitledBorder("Tipo De Usuario:"));

        javax.swing.GroupLayout panel_informacionUsuarioLayout = new javax.swing.GroupLayout(panel_informacionUsuario);
        panel_informacionUsuario.setLayout(panel_informacionUsuarioLayout);
        panel_informacionUsuarioLayout.setHorizontalGroup(
            panel_informacionUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_informacionUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_informacionUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(textField_UsuarioTipo, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
                    .addComponent(textField_usuarioEmail)
                    .addComponent(textField_usuarioNombre))
                .addContainerGap(511, Short.MAX_VALUE))
        );
        panel_informacionUsuarioLayout.setVerticalGroup(
            panel_informacionUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_informacionUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textField_usuarioNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textField_usuarioEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textField_UsuarioTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panel_perfilUsuarioLayout = new javax.swing.GroupLayout(panel_perfilUsuario);
        panel_perfilUsuario.setLayout(panel_perfilUsuarioLayout);
        panel_perfilUsuarioLayout.setHorizontalGroup(
            panel_perfilUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_perfilUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel_informacionUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panel_perfilUsuarioLayout.setVerticalGroup(
            panel_perfilUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_perfilUsuarioLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(panel_informacionUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(181, Short.MAX_VALUE))
        );

        paneles_presta.addTab("Perfil De Usuario", panel_perfilUsuario);

        panel_agregarMateriales.setBackground(new java.awt.Color(255, 255, 255));

        panel_inventario.setBorder(javax.swing.BorderFactory.createTitledBorder("Inventario"));

        table_inventario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id", "Nombre", "Necesita Potencia", "Necesita Descripcion"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        scrollPane_inventario.setViewportView(table_inventario);

        javax.swing.GroupLayout panel_inventarioLayout = new javax.swing.GroupLayout(panel_inventario);
        panel_inventario.setLayout(panel_inventarioLayout);
        panel_inventarioLayout.setHorizontalGroup(
            panel_inventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_inventarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollPane_inventario, javax.swing.GroupLayout.DEFAULT_SIZE, 513, Short.MAX_VALUE)
                .addContainerGap())
        );
        panel_inventarioLayout.setVerticalGroup(
            panel_inventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_inventarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollPane_inventario, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        panel_agregarMaterial.setBorder(javax.swing.BorderFactory.createTitledBorder("Material A Agregar"));

        textField_nombreMaterial.setBorder(javax.swing.BorderFactory.createTitledBorder("Nombre:"));

        checkBox_Potencia.setText("Potencia");

        checkBox_descripcion.setText("Descripción");

        javax.swing.GroupLayout panel_agregarMaterialLayout = new javax.swing.GroupLayout(panel_agregarMaterial);
        panel_agregarMaterial.setLayout(panel_agregarMaterialLayout);
        panel_agregarMaterialLayout.setHorizontalGroup(
            panel_agregarMaterialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_agregarMaterialLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_agregarMaterialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textField_nombreMaterial)
                    .addGroup(panel_agregarMaterialLayout.createSequentialGroup()
                        .addGroup(panel_agregarMaterialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(checkBox_Potencia, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(checkBox_descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 141, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panel_agregarMaterialLayout.setVerticalGroup(
            panel_agregarMaterialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_agregarMaterialLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textField_nombreMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkBox_Potencia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkBox_descripcion)
                .addContainerGap(198, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panel_agregarMaterialesLayout = new javax.swing.GroupLayout(panel_agregarMateriales);
        panel_agregarMateriales.setLayout(panel_agregarMaterialesLayout);
        panel_agregarMaterialesLayout.setHorizontalGroup(
            panel_agregarMaterialesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_agregarMaterialesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel_agregarMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panel_inventario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panel_agregarMaterialesLayout.setVerticalGroup(
            panel_agregarMaterialesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_agregarMaterialesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_agregarMaterialesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panel_inventario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel_agregarMaterial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(92, Short.MAX_VALUE))
        );

        paneles_presta.addTab("AgregarMateriales", panel_agregarMateriales);

        panel_consultarMisPrestamos.setBackground(new java.awt.Color(255, 255, 255));

        panel_filtroMateriales.setBackground(new java.awt.Color(255, 255, 255));
        panel_filtroMateriales.setBorder(javax.swing.BorderFactory.createTitledBorder("Filtros para la tabla"));

        comboBox_materialFiltro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        textField_descripcionFiltro.setBorder(javax.swing.BorderFactory.createTitledBorder("Descripción"));

        comboBox_estadoFiltro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Devuelto", "Prestado" }));

        textField_numPrestadosFiltro.setEditable(false);
        textField_numPrestadosFiltro.setBorder(javax.swing.BorderFactory.createTitledBorder("No. Préstamo Prestados"));

        textField_numDevueltosFIltro.setEditable(false);
        textField_numDevueltosFIltro.setBorder(javax.swing.BorderFactory.createTitledBorder("No. Préstamos Devueltos"));

        label_misPrestamosMaterial.setText("Material");

        label_estadoMaterial.setText("Estado");

        javax.swing.GroupLayout panel_filtroMaterialesLayout = new javax.swing.GroupLayout(panel_filtroMateriales);
        panel_filtroMateriales.setLayout(panel_filtroMaterialesLayout);
        panel_filtroMaterialesLayout.setHorizontalGroup(
            panel_filtroMaterialesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_filtroMaterialesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_filtroMaterialesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textField_descripcionFiltro)
                    .addComponent(comboBox_estadoFiltro, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textField_numPrestadosFiltro)
                    .addComponent(textField_numDevueltosFIltro)
                    .addGroup(panel_filtroMaterialesLayout.createSequentialGroup()
                        .addGroup(panel_filtroMaterialesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboBox_materialFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_misPrestamosMaterial)
                            .addComponent(label_estadoMaterial))
                        .addGap(0, 99, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panel_filtroMaterialesLayout.setVerticalGroup(
            panel_filtroMaterialesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_filtroMaterialesLayout.createSequentialGroup()
                .addComponent(label_misPrestamosMaterial)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboBox_materialFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textField_descripcionFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label_estadoMaterial)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboBox_estadoFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(textField_numPrestadosFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textField_numDevueltosFIltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        panel_prestamos.setBackground(new java.awt.Color(255, 255, 255));
        panel_prestamos.setBorder(javax.swing.BorderFactory.createTitledBorder("Préstamos"));

        table_prestamos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Material", "Descripción", "Fecha Pedido", "Fecha Devuelto"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(table_prestamos);

        javax.swing.GroupLayout panel_prestamosLayout = new javax.swing.GroupLayout(panel_prestamos);
        panel_prestamos.setLayout(panel_prestamosLayout);
        panel_prestamosLayout.setHorizontalGroup(
            panel_prestamosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_prestamosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 541, Short.MAX_VALUE)
                .addContainerGap())
        );
        panel_prestamosLayout.setVerticalGroup(
            panel_prestamosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_prestamosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout panel_consultarMisPrestamosLayout = new javax.swing.GroupLayout(panel_consultarMisPrestamos);
        panel_consultarMisPrestamos.setLayout(panel_consultarMisPrestamosLayout);
        panel_consultarMisPrestamosLayout.setHorizontalGroup(
            panel_consultarMisPrestamosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_consultarMisPrestamosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel_filtroMateriales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panel_prestamos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panel_consultarMisPrestamosLayout.setVerticalGroup(
            panel_consultarMisPrestamosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_consultarMisPrestamosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_consultarMisPrestamosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panel_prestamos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel_filtroMateriales, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(112, Short.MAX_VALUE))
        );

        paneles_presta.addTab("Consultar Mis Préstamos", panel_consultarMisPrestamos);

        panel_titulo.setBackground(new java.awt.Color(204, 204, 255));

        label_titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_titulo.setText("Prestamo (prototipo)");
        label_titulo.setToolTipText("");

        javax.swing.GroupLayout panel_tituloLayout = new javax.swing.GroupLayout(panel_titulo);
        panel_titulo.setLayout(panel_tituloLayout);
        panel_tituloLayout.setHorizontalGroup(
            panel_tituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_titulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panel_tituloLayout.setVerticalGroup(
            panel_tituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_titulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        label_titulo.getAccessibleContext().setAccessibleName("");

        label_nombreDelUsuario.setText("Usuario nombre");

        javax.swing.GroupLayout panel_nombreDelUsuarioLayout = new javax.swing.GroupLayout(panel_nombreDelUsuario);
        panel_nombreDelUsuario.setLayout(panel_nombreDelUsuarioLayout);
        panel_nombreDelUsuarioLayout.setHorizontalGroup(
            panel_nombreDelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_nombreDelUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_nombreDelUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                .addContainerGap())
        );
        panel_nombreDelUsuarioLayout.setVerticalGroup(
            panel_nombreDelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_nombreDelUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_nombreDelUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(paneles_presta, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(panel_titulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel_nombreDelUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(panel_nombreDelUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(paneles_presta))
        );

        paneles_presta.getAccessibleContext().setAccessibleName("");

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrestaInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrestaInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrestaInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrestaInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        ArrayList<Usuario> usuarios;
        usuarios = new ArrayList();
        Administrador admin1 = new Administrador("Josue Peñuelas Torres", "penuelas.josue@uabc.edu.mx", 0);
        Tutor tutor1 = new Tutor("Linda Eugenia Arredondo Acosta", "linda_arredondo@uabc.edu.mx");
        Alumno alum1 = new Alumno(1169153, tutor1, "Alfonso Trejo Robles", "trejo.alfonso@uabc.edu.mx", 3);
        usuarios.add(admin1);
        usuarios.add(alum1);
        String s = JOptionPane.showInputDialog("introduzca su correo: ");
        
         Usuario usuarioEncontrado = null;

        for (Usuario usuario : usuarios) {
            if (usuario.getCorreo().equals(s)) {
                usuarioEncontrado = usuario;
                break;
            }
        }
        
        if (usuarioEncontrado != null) {
            System.out.println("Usuario encontrado");
            String nombre = usuarioEncontrado.getNombre();
        } else {
            System.out.println("Usuario no encontrado.");
        }
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrestaInterfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_agregarMaterial;
    private javax.swing.JButton button_enviarPrestamo;
    private javax.swing.JCheckBox checkBox_Potencia;
    private javax.swing.JCheckBox checkBox_descripcion;
    private javax.swing.JComboBox<String> comboBox_Potenciador;
    private javax.swing.JComboBox<String> comboBox_cantidad;
    private javax.swing.JComboBox<String> comboBox_estadoFiltro;
    private javax.swing.JComboBox<String> comboBox_materialFiltro;
    private javax.swing.JComboBox<String> comboBox_materiales;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_cantidad;
    private javax.swing.JLabel label_estadoMaterial;
    private javax.swing.JLabel label_generarPrestamoMaterial;
    private javax.swing.JLabel label_misPrestamosMaterial;
    private javax.swing.JLabel label_nombreDelUsuario;
    private javax.swing.JLabel label_potenciador;
    private javax.swing.JLabel label_prestamo;
    private javax.swing.JLabel label_titulo;
    private javax.swing.JPanel panel_agregarMaterial;
    private javax.swing.JPanel panel_agregarMateriales;
    private javax.swing.JPanel panel_consultarMisPrestamos;
    private javax.swing.JPanel panel_filtroMateriales;
    private javax.swing.JPanel panel_generarPrestamo;
    private javax.swing.JPanel panel_informacionUsuario;
    private javax.swing.JPanel panel_inventario;
    private javax.swing.JPanel panel_material;
    private javax.swing.JPanel panel_nombreDelUsuario;
    private javax.swing.JPanel panel_perfilUsuario;
    private javax.swing.JPanel panel_prestamo;
    private javax.swing.JPanel panel_prestamos;
    private javax.swing.JPanel panel_titulo;
    private javax.swing.JTabbedPane paneles_presta;
    private javax.swing.JScrollPane scrollPane_inventario;
    private javax.swing.JScrollPane scrollPane_materialesPrestamo;
    private javax.swing.JTable table_inventario;
    private javax.swing.JTable table_materialesPrestamo;
    private javax.swing.JTable table_prestamos;
    private javax.swing.JTextField textField_UsuarioTipo;
    private javax.swing.JTextField textField_descripcion;
    private javax.swing.JTextField textField_descripcionFiltro;
    private javax.swing.JTextField textField_nombreMaterial;
    private javax.swing.JTextField textField_numDevueltosFIltro;
    private javax.swing.JTextField textField_numPrestadosFiltro;
    private javax.swing.JTextField textField_usuarioEmail;
    private javax.swing.JTextField textField_usuarioNombre;
    // End of variables declaration//GEN-END:variables
}
